name: "Build btrbk container"

on:
  push:
  schedule:
    - cron:  '0 0 * * MON'

env:
  IMAGE_NAME: btrbk
  IMAGE_TAG: latest
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}


jobs:
  build-and-publish-image:
    name: Build image
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to ghcr.io
        uses: redhat-actions/podman-login@v1
        with:
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN }}
            registry: ${{ env.IMAGE_REGISTRY }}

      - name: Build and push container
        uses: coreos/actions-lib/build-container@main
        with:
          arches: 'amd64 arm64'
          file: Containerfile
          credentials: ${{ env.REGISTRY_AUTH_FILE }}
          push: ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}


          #      - name: Push to registry
          #id: push-to-ghcr
          # run: podman push build ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
